image: python:3.7.0

# Change pip's cache directory to be inside the project directory since we can
# # only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
#
#     # Pip's cache doesn't store the python packages
#     # https://pip.pypa.io/en/stable/reference/pip_install/#caching
#     #
#     # If you want to also cache the installed packages, you have to install
#     # them in a virtualenv and cache it as well.



before_script:
        #  - apt-get update -y && apt-get install libhdf5-serial-dev -y
  - python -V               # Print out python version for debugging
  - python -m venv venv
  - source venv/bin/activate
  - pip install -U pip
  - pip install poetry
  - poetry install

stages:
  - test

check_code:
  tags:
  - modern
  stage: test
  script:
  - mkdir cert
  - echo "$ca_cert" > "./cert/Proteomicsdb-Prosit.crt"
  - echo "$cert" > "./cert/ci-pipeline.crt"
  - echo "$key" > "./cert/ci-pipeline.key"
  - py.test --junitxml=junit.xml

  artifacts:
    reports:
      junit: tests/junit.xml

