[tool.poetry]
name = "prosit_grpc"
version = "0.1.0"
description = "A Client to access Prosit via GRPC"
authors = ["Daniela Andrade Salazar <danial.andrade@tum.de>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "1.17.4"
scikit-learn = "0.21.3"
tensorflow = "1.14.0"
tensorflow-serving-api = "1.14.0"
grpcio = "1.25.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
