[tool.poetry]
name = "prosit_grpc"
version = "0.1.0"
description = "A Client to access Prosit via GRPC"
authors = ["Daniela Andrade Salazar <danial.andrade@tum.de>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.18.1"
scikit-learn = "^0.21.3"
tensorflow = "^1.15.2"
tensorflow-serving-api = "^1.15.0"
grpcio = "^1.26.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


[tool.pytest]
addopts ='''
   -rEfswx
    --ignore=setup.py
    --ignore=.eggs
    --doctest-modules
    --cov pwyll
    --cov-report term-missing
'''
